services:
  # Action Server
  - type: web
    name: action-server
    env: docker
    dockerfilePath: rasa/Dockerfile.actions
    dockerContext: .
    plan: free
    private: true
    envVars:
      - key: PORT
        value: 5055

  # Rasa Server
  - type: web
    name: rasa-server
    env: docker
    dockerfilePath: rasa/Dockerfile.rasa
    dockerContext: .
    plan: free
    envVars:
      - key: ACTION_SERVER_URL
        value: https://action-server:5055
      - key: PORT
        value: 5005

  # Frontend
  - type: web
    name: frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l $PORT
    rootDir: rasa/frontend
    envVars:
      - key: NODE_VERSION
        value: 16.0.0
      - key: REACT_APP_RASA_SERVER_URL
        value: https://rasa-server:5005