services:
  # Action Server (Private)
  - type: web
    name: action-server
    env: docker
    dockerfilePath: rasa/Dockerfile.actions
    dockerContext: .
    plan: free
    private: true  # This makes it a private service
    startCommand: "run actions"

  # Rasa Server (Public)
  - type: web
    name: rasa-server
    env: docker
    dockerfilePath: rasa/Dockerfile.rasa
    dockerContext: .
    plan: free
    envVars:
      - key: ACTION_SERVER_URL
        fromService:
          type: web  # Changed from 'pvt' to 'web'
          name: action-server
          property: url
      - key: RASA_TELEMETRY_ENABLED
        value: false
    startCommand: "run --enable-api --cors \"*\" -p $PORT --endpoints endpoints.yml --model /app/models"

  # Frontend (React Static Site)
  - type: static
    name: frontend
    rootDir: rasa/frontend
    buildCommand: "npm install && npm run build"
    publishDir: "./build"
    envVars:
      - key: REACT_APP_RASA_SERVER_URL
        fromService:
          type: web
          name: rasa-server
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html