services:
  # Action Server (Private)
  - type: pserv
    name: action-server
    env: docker
    dockerfilePath: ./rasa/Dockerfile.actions
    dockerContext: .
    plan: free

  # Rasa Server (Public)
  - type: web
    name: rasa-server
    env: docker
    dockerfilePath: ./rasa/Dockerfile.rasa
    dockerContext: .
    plan: free
    envVars:
      - key: ACTION_SERVER_URL
        fromService:
          type: pserv
          name: action-server
          property: host
      - key: RASA_TELEMETRY_ENABLED
        value: false
      - key: PORT
        value: 5005

  # Frontend (React Static Site)
  - type: web
    name: frontend
    env: static
    buildCommand: "npm install && npm run build"
    rootDir: ./rasa/frontend
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_RASA_SERVER_URL
        fromService:
          type: web
          name: rasa-server
          property: host
    staticHeaders:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html