services:
  # Action Server
  - type: web
    name: action-server
    env: docker
    dockerfilePath: rasa/Dockerfile.actions
    dockerContext: .
    plan: free
    private: true
    startCommand: "run actions"
    envVars:
      - key: PORT
        value: 5055

  # Rasa Server
  - type: web
    name: rasa-server
    env: docker
    dockerfilePath: rasa/Dockerfile.rasa
    dockerContext: .
    plan: free
    envVars:
      - key: ACTION_SERVER_URL
        fromService:
          type: web
          name: action-server
          property: url
      - key: RASA_TELEMETRY_ENABLED
        value: "false"
      - key: PORT
        value: 5005
    startCommand: "run --enable-api --cors \"*\" -p $PORT --endpoints endpoints.yml --model /app/models"

  # Frontend as a Web Service (not static)
  - type: web
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    startCommand: npm install -g serve && serve -s build -l $PORT
    buildFilter:
      paths:
      - rasa/frontend/**
    rootDir: rasa/frontend
    envVars:
      - key: REACT_APP_RASA_SERVER_URL
        fromService:
          type: web
          name: rasa-server
          property: url