services:
  # Action Server (Private)
  - type: pvt
    name: action-server
    env: docker
    # Note: Dockerfile paths are relative to project root
    dockerfilePath: rasa/Dockerfile.actions
    dockerContext: .
    plan: free

  # Rasa Server (Public)
  - type: web
    name: rasa-server
    env: docker
    dockerfilePath: rasa/Dockerfile.rasa
    dockerContext: .
    plan: free
    envVars:
      - key: ACTION_SERVER_URL
        fromService:
          type: pvt
          name: action-server
          property: url
      - key: RASA_TELEMETRY_ENABLED
        value: false
    startCommand: "run --enable-api --cors \"*\" -p $PORT --endpoints endpoints.yml --model /app/models"

  # Frontend (React Static Site)
  - type: static
    name: frontend
    # Update rootDir to point to frontend from project root
    rootDir: rasa/frontend
    buildCommand: "npm install && npm run build"
    publishDir: "./build"
    envVars:
      - key: REACT_APP_RASA_SERVER_URL
        fromService:
          type: web
          name: rasa-server
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html